{% set name = "lcensemble" %}
{% set version = "0.2.9" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/lcensemble-{{ version }}.tar.gz
  sha256: f3d5d3c538ee26d749ec50062b2d7dd68ab701cb1b52fbca2c6095eeeea19795

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7
    - numpy ==1.21.5
    - pandas ==1.3.5
    - xgboost ==1.5.0
    - scikit-learn ==1.0.2
    - hyperopt ==0.2.7

test:
  imports:
    - lce
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://lce.readthedocs.io/en/latest/
  summary: Local Cascade Ensemble package
  license: Apache-2.0
  license_file:
    - LICENSE

extra:
  recipe-maintainers:
    - LocalCascadeEnsemble
